### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by chengwei0427** [ZikangYuan/liw_oam#1]
Hi, @ZikangYuan 

   Thanks for your great work. I'm very interested in the tightly-coupled lidar+imu+encoder framework, and can you upload the test dataset in [**baidu yun**](). I think it's very friendly to  the people in mainland china.

   Thanks again.

**Comment by ZikangYuan** [comment]
OK, I will upload the test dataset to baidu yun as soon as possible.

**Comment by chengwei0427** [comment]
Glad to hear that. 
I'll check the update and thank your for your contribution.

**Comment by TianleXuA** [comment]
The baidu yun link has been added.

**Comment by ZikangYuan** [comment]
The baidu yun link has been added.

**Comment by chengwei0427** [comment]
Nice work. Problem solved. Thanks again.
