### ISSUE TITLE
Could bother author to upload kaist_2 and kaist_3 from baidu yun onto google drive?

### ISSUE THREAD

**Issue by narutojxl** [ZikangYuan/liw_oam#10]
Hello doctor @ZikangYuan,
I download kaist_2 and kaist_3,  and then with [ZikangYuan/kaist2bag](https://github.com/ZikangYuan/kaist2bag) tool to create bags. Edit the config file with path and desired topics config.yaml, use `rosbag info velodyne_points.bag` and `rosbag info velocity.bag` i can see the detailed info and rosbag play is also OK. 
But when as to about imu bags, they are all empty.  I tried twice the process, but the result is the same, i don't figure out something is wrong.
As for download speed from baidu yun  is very very slow, could  bother you to upload kaist_2 and kaist_3 from baidu yun onto google drive? 
Thanks for your help and time in advance!
Best regards
>
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ rosbag info xsens_imu_data.bag 
	path:    xsens_imu_data.bag
	version: 2.0
	size:    4.0 KB
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ 
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ 
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ rosbag info imu_data_raw.bag 
	path:    imu_data_raw.bag
	version: 2.0
	size:    4.0 KB
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ 
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$ rosbag info imu_mag.bag 
	path:    imu_mag.bag
	version: 2.0
	size:    4.0 KB
	jxl@hp:/media/jxl/Windows/bags/KAIST/urban02/urban02_old/test_bag$

**Comment by ZikangYuan** [comment]
Ok, I am uploading all kaist bag.

**Comment by narutojxl** [comment]
Thanks doctor @ZikangYuan, very very much, close it now!

**Comment by ZikangYuan** [comment]
I'm sorry for misreading your issue. The Google Drive has a limited capacity of only 15GB, so I couldn't transfer the bag to Google Drive.
