### ISSUE TITLE
关于论文中轮速观测量引入的问题

### ISSUE THREAD

**Issue by zhh2005757** [ZikangYuan/liw_oam#11]
作者您好，看到论文里一方面将轮速与IMU构建了IMU轮速预积分残差，另一方面又采用了轮速速度用作IMU速度约束残差，想问下这两种残差形式同时都使用到轮速观测量，在概率意义上难道不应该是相关的吗，这样的话是否就违背了MAP中残差独立才可以彼此相加的原理？

**Comment by ZikangYuan** [comment]
我的理解是这样：轮速计的测量值，可以直接用来约束速度这个状态量，轮速计的预积分，可以用来约束平移这个状态量。速度和平移之间是有运动学约束关系存在的，换言之，他们是相关的。但我并不认为轮速计的速度观测约束和预积分约束是不能加在一起的，就像IMU预积分会同时约束速度，平移还有旋转，但是彼此之间也是相关的。按照更严谨的做法，轮速计速度观测约束的权重应该根据轮速计测量噪声的大小来建模，就像预积分是根据IMU噪声传播理论推演而来一样。我们这个work比较粗糙，没有对速度观测约束进行严谨的建模，所以可能给了你“不相关”的感觉。

**Comment by zhh2005757** [comment]
感谢作者的解答。还想请问下，既然轮速可以直接约束IMU速度，而根据IMU的原理速度可以进一步影响位置，那么为什么又采用轮速预积分再对速度进行约束呢？反之也是同样的疑问，如果用轮速预积分对位置进行了约束，还有必要对速度再进行约束吗？其中的差异作者是如何考虑的呢？因为我看的比较多的是了轮速位置预积分与轮速直接约束二选其一，作者两个都采用了比较新颖，所以了解下这样做的意义。

**Comment by ZikangYuan** [comment]
因为速度和平移本身都是待优化状态量，所以用轮速计速度测量值用来约束速度，用轮速计预积分来约束平移是并不冲突的。就这两种约束的特性而言：轮速计速度测量值的约束具备“瞬时性”，只要当下采集到这个测量值的时刻汽车不存在打滑现象，那么这个值构建的约束就是靠谱的。轮速计预积分具备“持续性”，如果这段时间内出现打滑，那么预积分就不靠谱，但反过来，由于它是对一段时间内的测量值进行积分，会削弱噪声带来的影响。各有各的好吧

**Comment by zhh2005757** [comment]
感谢解答！
