### ISSUE TITLE
外参extrinsic_t_odom, extrinsic_R_odom指的是什么？

### ISSUE THREAD

**Issue by pengjili** [ZikangYuan/liw_oam#12]
您好，感谢你的work，有一个问题是extrinsic_t_odom和extrinsic_R_odom它指的是哪个到哪个的变换呢？  而且我看代码里好像并没有实际用到这两个变量对吗？

**Comment by ZikangYuan** [comment]
您好，这两个量都是轮速计到IMU的外参。之前的代码中确实没用到，这是我们的疏忽，感谢您的指正。但结果并不受影响，因为nclt和kaist这两个数据集extrinsic_R_odom都是单位阵。更新后的代码已添加了对extrinsic_R_odom的使用。
