### ISSUE TITLE
ground_truth

### ISSUE THREAD

**Issue by Liming-Cheng** [ZikangYuan/liw_oam#13]
作者您好，想咨询下关于nclt ground truth的问题：
1. readme中提供的下载链接内，获取到的nclt.txt是乱码，kaist.txt ok；
2. 读取了ground_truth.csv之后发现外参有问题，请教下如何将groundtruth转到bag中已经做过处理的imu系下，有点疑惑。
3. 可以麻烦您check下上传的nclt ground truth吗？感谢！

**Comment by ZikangYuan** [comment]
您好，nclt的GT已重新上传。至于外参转换问题，假设GT到IMU的外参变换是T_ig，对于任意时刻gt坐标系下的pose T_cur_g，只需要通过T_cut_i = T_ig * T_cur_g * T_ig.transpose() 就能将GT的pose从GT坐标系转到IMU坐标系。
