### ISSUE TITLE
有关nclt数据集轮速计和imu的外参问题

### ISSUE THREAD

**Issue by JIANG-CX** [ZikangYuan/liw_oam#14]
您好，我发现nclt所使用的平衡车在行驶过程中会前后摇摆，会导致imu和轮速计的外参不断变化，但融合imu和轮速的时候需要知道这个外参，请问是如何处理这个问题的呢？谢谢。

**Comment by ZikangYuan** [comment]
您好，LIWO中并没有处理该问题。或许您可以尝试将外参作为变量一起参与优化(但可能效果并不好)。

**Comment by JIANG-CX** [comment]
> 您好，LIWO中并没有处理该问题。或许您可以尝试将外参作为变量一起参与优化(但可能效果并不好)。

感谢您的回复，但如果不处理这个问题的话，融合不会有错误吗？nclt中平衡车前后摇摆的还是很明显的，没有外参的话，两个传感器如何融合呢？谢谢。

**Comment by 0ontheroad** [comment]
您好，可以发一份lio-sam关于nclt数据集的配置文件吗，如果可以的话，真的万分感谢！！！邮箱：13093776085@163.com

**Comment by ZikangYuan** [comment]
其实LIWO这个系统并不完善，它只提供了一个基础框架，关于外参优化，转弯时左右轮速度不一致，以及打滑等问题均未进行处理。根据我们目前的测试结果，NCLT的外参问题并不会特别影响里程计的定位精度。
如果没有外参，我的建议是将外参添加进优化问题中，这个可能没法彻底把这个问题解决好，但也会有所改善。

**Comment by JIANG-CX** [comment]
好的，谢谢你的回复

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zikang Yuan ***@***.***>
发送时间: Sunday, April 7, 2024 3:14:25 PM
收件人: ZikangYuan/liw_oam ***@***.***>
抄送: JIANG Chenxing ***@***.***>; Author ***@***.***>
主题: Re: [ZikangYuan/liw_oam] 有关nclt数据集轮速计和imu的外参问题 (Issue #14)


其实LIWO这个系统并不完善，它只提供了一个基础框架，关于外参优化，转弯时左右轮速度不一致，以及打滑等问题均未进行处理。根据我们目前的测试结果，NCLT的外参问题并不会特别影响里程计的定位精度。
如果没有外参，我的建议是将外参添加进优化问题中，这个可能没法彻底把这个问题解决好，但也会有所改善。

―

**Comment by JIANG-CX** [comment]
您好，还想请问一下nclt提供的真值pose是什么传感器在什么坐标系下的呢？谢谢。
