### ISSUE TITLE
您好，可以发一份lio-sam关于nclt数据集的配置文件吗，如果可以的话，真的万分感谢！！！邮箱：13093776085@163.com

### ISSUE THREAD

**Issue by 0ontheroad** [ZikangYuan/liw_oam#15]
您好，可以发一份lio-sam关于nclt数据集的配置文件吗，如果可以的话，真的万分感谢！！！邮箱：[13093776085@163.com]

**Comment by ZikangYuan** [comment]
已发，祝顺利。

**Comment by YuexinMu** [comment]
@ZikangYuan 您好，您可以也发我一份吗？万分感谢！！！202324021066t@stu.cqu.edu.cn

**Comment by Thegraeat** [comment]
> 已发，祝顺利。

您好，发一份liosam对nclt的配置吗？万分感谢！jin11208@163.com

**Comment by zyf-sdu** [comment]
@ZikangYuan 您好，可以也发我一份吗？万分感谢！！1123409905@qq.com
