### ISSUE TITLE
readme出错

### ISSUE THREAD

**Issue by studyboom** [ZikangYuan/liw_oam#3]
你好，你们的命令有一个好像输错了

![360截图16720327326968](https://user-images.githubusercontent.com/38801096/232424808-4e0ec748-72f4-4c58-94c1-6ebdbc8dc0e7.png)
应该是source吧

**Comment by studyboom** [comment]
liw_oam应该改为liw-oam吧

**Comment by studyboom** [comment]
liw_oam应该改为liw-oam嘛，希望对你们有帮助，同时谢谢你们的项目，是一个很好的项目，很有帮助。

**Comment by ZikangYuan** [comment]
感谢您的建议，source的问题已改。之所以命名为liw_oam而不命名为liw-oam，是因为ROS里的pkg命名是不允许包含大写字母和"-"符号的，否则会出错。

**Comment by studyboom** [comment]
嗯，谢谢你们的回复
