### ISSUE TITLE
running nclt dataset failed 

### ISSUE THREAD

**Issue by narutojxl** [ZikangYuan/liw_oam#4]
Hello author,
Thanks for your sharing!  I want to run the demo with nclt dataset as following.
*  TypeError: can't set attributes of built-in/extension type 'scipy.spatial.transform.rotation.Rotation'
`python3 ./nclt_to_rosbag_10Hz.py  /media/jxl/Windows/bags/NCLT/2013-01-10/  /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag`
>
   	3092680.5714285714
	100%|██████████████████████████████████████████████████████████████████████▉| 2771040008/2771041792 [13:15<00:00, 3483668.80it/s]
	48324
	48315
	Traceback (most recent call last):
	  File "./nclt_to_rosbag_10Hz.py", line 500, in <module>
	    sys.exit(main(sys.argv))
	  File "./nclt_to_rosbag_10Hz.py", line 429, in main
	    write_ms25(ms25, ms25_euler, i_ms25, bag)
	  File "./nclt_to_rosbag_10Hz.py", line 189, in write_ms25
	    r_q = R.r = R.from_euler('xyz', [h, p, r], degrees=0)
	TypeError: can't set attributes of built-in/extension type 'scipy.spatial.transform.rotation.Rotation'
* rosbag broken.
> 
    	rosbag play /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag --clock -d 1.0 -r 1.0
	[ INFO] [1685539319.206905517]: Opening /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag
	Bag file /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag is unindexed.  Run rosbag reindex.
	$rosbag reindex /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag
	 /media/jxl/Windows/bags/NCLT/2013-01-10/2013-01-10.bag                                       100%              7.0 GB 00:06

*  run demo, it only always outputs `Failed to find match for field 'intensity'.` and in rviz, there is nothing.
>
	rosbag play ./2013-01-10.bag --clock -d 1.0 -r 1.0
	roslaunch liw_oam liw_nclt.launch

**Comment by narutojxl** [comment]
with kaist_1.bag on [baidu yun](https://pan.baidu.com/s/1vrat2HdTf6NBrjw_kGCZNw) can normally run demo, close it now.

**Comment by dxdydz3dt** [comment]
Did solve the above problem?

**Comment by narutojxl** [comment]
> Did solve the above problem?
No.
