### ISSUE TITLE
疑问1

### ISSUE THREAD

**Issue by liyd0306** [ZikangYuan/liw_oam#5]
大佬好，我在跑数据集kaist，在rostopic echo /Velocity的地方发现了xy在同时变化，z不变，角度也没有变化。请问：xy为啥在同时变化呢？单位是m/s吗？这个话题的信息总体来说没太能理解清楚，还望您能费心解答一下哈

**Comment by EinsTian1** [comment]
> 大佬好，我在跑数据集kaist，在rostopic echo /Velocity的地方发现了xy在同时变化，z不变，角度也没有变化。请问：xy为啥在同时变化呢？单位是m/s吗？这个话题的信息总体来说没太能理解清楚，还望您能费心解答一下哈

x,y是指左右轮速度，z是不含有数据的，轮速计是根据脉冲次数计算速度的，是个标量，没有方向，所以没有角度信息。
