### ISSUE TITLE
疑问2

### ISSUE THREAD

**Issue by liyd0306** [ZikangYuan/liw_oam#6]
大佬好，非常想跑通您此算法的实测来感受效果。目前雷达惯导里程计等一些的话题都对上了，但RVIZ上没有地图的显示。我附带了一些截图，是我试验的过程，还望大佬有空方便的时候看看，指点一二，很感谢。
![1](https://github.com/ZikangYuan/liw_oam/assets/73767168/e8e88f05-fb0a-4ff5-91cf-654722312a79)
![2](https://github.com/ZikangYuan/liw_oam/assets/73767168/46a39b9f-71aa-404e-9716-eeb080f22000)
![3](https://github.com/ZikangYuan/liw_oam/assets/73767168/73d71b86-d09b-4af7-b258-2126ae02ecdb)
![4](https://github.com/ZikangYuan/liw_oam/assets/73767168/f9647328-3209-4e76-8257-75c1d2af9b96)

**Comment by EinsTian1** [comment]
> 

请问你用的是自己的数据集还是我们使用的公开数据集？雷达型号是什么？可以参考cloudprocessing.h文件，写一下自己用的数据集雷达型号

**Comment by EinsTian1** [comment]
> 感谢您费心了，我使用的是禾赛雷达XT-32线，公开数据集我跑通了。然后紧接着试了一下自己的实测，没有跑通。地图上没有显示但是都对齐了的
要实测该型号雷达，需要对代码进行部分修改，主要是雷达数据接收这一部分。

**Comment by EinsTian1** [comment]
> 感谢您费心了，我使用的是禾赛雷达XT-32线，公开数据集我跑通了。然后紧接着试了一下自己的实测，没有跑通。地图上没有显示但是都对齐了的

要实测该型号雷达，需要对代码进行部分修改，主要是雷达数据接收这一部分。

**Comment by liyd0306** [comment]
衷心感谢，我再仔细看看研究一下
