### ISSUE TITLE
kaist velodyne imu 外参

### ISSUE THREAD

**Issue by kkkiddd** [ZikangYuan/liw_oam#7]
您好，在kaist config中外参是：
extrinsic_parameter:
    extrinsic_enable:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_t: [ 0.58743, -0.02924, -0.175676276933]
    extrinsic_R: [ -0.515105,-0.702383,-0.491249,
                   0.487008,-0.711468,0.506593,
                   -0.70533,0.0217062,0.708547]
    extrinsic_t_odom: [ 0.0, 0.0, 0.0]
    extrinsic_R_odom: [ 1.0, 0.0, 1.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0 ]

1. extrinsic_R与urban8的Vehicle2LeftVLP外参一致，但是extrinsic_t在urban8中是T: -0.438343 0.395882 1.94095。 想问一下  extrinsic_t: [ 0.58743, -0.02924, -0.175676276933]这个数据是从哪里得来的？
2.  我试着用您给的kaist2bag生成其他的kaist rosbag时， 点云转换会出现以下error，这是为什么呢？
![Screenshot 2023-06-01 16:58:51](https://github.com/ZikangYuan/liw_oam/assets/135218325/1676b7bb-7ecd-4e4c-9f06-5b7455754ba0)

**Comment by kkkiddd** [comment]
感谢您的回答，但是对于问题1,我还有点问题。 以urban8来说，
Vehicle2LeftVLP：
R: -0.515105 -0.702383 -0.491249 0.487008 -0.711468 0.506593 -0.70533 0.0217062 0.708547 
T: -0.438343 0.395882 1.94095
Vehicle2IMU：
R: 1 0 0 0 1 0 0 0 1 
T: -0.07 0 1.7
那么LeftVLP2IMU的外参应该是：
R: -0.515105 -0.702383 -0.491249 0.487008 -0.711468 0.506593 -0.70533 0.0217062 0.708547 
T： -0.368343, 0.395882, 0.24095
不好意思，我还是个小白，这样计算外参错了吗？为什么t= 0.58743, -0.02924, -0.175676276933？

**Comment by EinsTian1** [comment]
> 感谢您的回答，但是对于问题1,我还有点问题。 以urban8来说， Vehicle2LeftVLP： R: -0.515105 -0.702383 -0.491249 0.487008 -0.711468 0.506593 -0.70533 0.0217062 0.708547 T: -0.438343 0.395882 1.94095 Vehicle2IMU： R: 1 0 0 0 1 0 0 0 1 T: -0.07 0 1.7 那么LeftVLP2IMU的外参应该是： R: -0.515105 -0.702383 -0.491249 0.487008 -0.711468 0.506593 -0.70533 0.0217062 0.708547 T： -0.368343, 0.395882, 0.24095 不好意思，我还是个小白，这样计算外参错了吗？为什么t= 0.58743, -0.02924, -0.175676276933？

平移是不能直接相加减的，要根据变换关系计算: T<sub>l</sub><sup>i</sup>=(T<sub>v</sub><sup>i</sup>)<sup>-1</sup>*T<sub>v</sub><sup>l</sup>
