### ISSUE TITLE
关于NCLT数据集的应用

### ISSUE THREAD

**Issue by PigletPh** [ZikangYuan/liw_oam#8]
您好，想请教下我用nclt_to_rosbag_10Hz.py成功制作nclt的bag包。但是我用fast-lio2和liw_oam都能成功运行，用lio-sam运行bag包，rviz中没有任何显示，请问您能指导下吗，谢谢！这是我修改后的configure文件：
lio_sam:

  # Topics
  pointCloudTopic: "/points_raw"               # Point cloud data
  imuTopic: "/imu_raw"                         # IMU data
  odomTopic: "odometry/imu"                   # IMU pre-preintegration odometry, same frequency as IMU
  gpsTopic: "odometry/gpsz"                   # GPS odometry topic from navsat, see module_navsat.launch file

  # Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  # GPS Settings
  useImuHeadingInitialization: false           # if using GPS data, set to "true"
  useGpsElevation: false                      # if GPS elevation is bad, set to "false"
  gpsCovThreshold: 2.0                        # m^2, threshold for using GPS data
  poseCovThreshold: 25.0                      # m^2, threshold for using GPS data
  
  # Export settings
  savePCD: false                              # https://github.com/TixiaoShan/LIO-SAM/issues/3
  savePCDDirectory: "/home/user/Desktop/scliosam/data/"  # use global path, and end with "/" 
    # warning: if you have already data in the above savePCDDirectory, it will all remove and remake them. Thus, backup is recommended if pre-made data exist. 

  # Sensor Settings
  sensor: velodyne                            # lidar sensor type, either 'velodyne' or 'ouster'
  N_SCAN: 32                               # number of lidar channel (i.e., 16, 32, 64, 128)
  Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.0                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0                       # default: 1000.0, maximum lidar range to be used

  # IMU Settings
  imuAccNoise: 0.1
  imuGyrNoise: 0.1
  imuAccBiasN: 0.0001
  imuGyrBiasN: 0.0001
  imuGravity: 9.80416
  imuRPYWeight: 0.01

  # Extrinsics (lidar -> IMU, of NCLT dataset)
  extrinsicTrans: [0.112, 0.176, -0.247]
  extrinsicRot: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]
  extrinsicRPY: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]

**Comment by ZikangYuan** [comment]
请留下您的邮箱，明早我会将我们配置好的lio-sam发给您

**Comment by PigletPh** [comment]
@ZikangYuan 好的，感谢您。另外我在用您这边的KAIST数据集时，跑fast-lio2时出现bag结束时，轨迹还没跑完，您能顺便发一下fast-lio2的kaist数据集配置嘛，十分感谢您。邮箱是712091209@qq.com，再次感谢您！

**Comment by ZikangYuan** [comment]
已发送至您邮箱。

**Comment by PigletPh** [comment]
> 已发送至您邮箱。
您好，我下载您发的lio-sam。在跑NCLT数据集时，出现以下警告：
[ WARN] [1688390957.872322420]: Large velocity, reset IMU-preintegration!
同时里程计开始漂移，如图
![4](https://github.com/ZikangYuan/liw_oam/assets/44089510/900a4793-0cbb-47c0-a1a3-b92526f09c4b)
另外，kaist数据集的yaml也有问题，您看一下，谢谢！

**Comment by Jopery** [comment]
> 请留下您的邮箱，明早我会将我们配置好的lio-sam发给您

您好，可以也发我一份吗，真的非常感谢您，这个问题困扰了我很长时间。这是我的邮箱：1050057267@qq.com

**Comment by Jopery** [comment]
> @ZikangYuan 好的，感谢您。另外我在用您这边的KAIST数据集时，跑fast-lio2时出现bag结束时，轨迹还没跑完，您能顺便发一下fast-lio2的kaist数据集配置嘛，十分感谢您。邮箱是[712091209@qq.com](mailto:712091209@qq.com)，再次感谢您！

您好，可以分享一下lio-sam运行NCLT的相关配置吗？万分感谢！

**Comment by justinyeah** [comment]
> 已发送至您邮箱。

您好，可以也发我一份吗，真的非常感谢您，这个问题困扰了我很长时间。这是我的邮箱：1344992670@qq.com
